--[[----------------------------------------------------------------------------

en.lua
English translations for PikSend Lightroom plugin

Covers requirements 13.1-13.10 for documentation and support

------------------------------------------------------------------------------]]

return {
  -- Plugin info
  pluginName = 'PikSend',
  pluginDescription = 'Export your photos directly to PikSend from Lightroom',
  pluginVersion = 'Version: $$/version',
  pluginAbout = 'About PikSend',
  pluginAboutDescription = 'Export your photos directly to PikSend from Lightroom.',
  pluginForLightroom = 'PikSend Plugin for Adobe Lightroom Classic',
  
  -- Authentication (Requirements 2.1-2.10)
  authTitle = 'PikSend Login',
  authConnected = 'Connected as: $$/name',
  authNotConnected = 'Not connected',
  authLogin = 'Login',
  authLogout = 'Logout',
  authTokenLabel = 'API Token:',
  authTokenPlaceholder = 'Enter your API token',
  authOpenDashboard = 'Open Dashboard',
  authInstructions = 'Generate an API token from your PikSend dashboard:',
  authSuccess = 'Login successful',
  authSuccessMessage = 'Welcome $$/name! You are now connected to PikSend.',
  authError = 'Authentication error',
  authErrorMessage = 'Invalid API token. Please check your token and try again.',
  authProRequired = 'Pro plan required',
  authProRequiredMessage = 'The Lightroom plugin is reserved for Pro users. Please upgrade your plan at piksend.com.',
  authTokenRequired = 'Token required',
  authTokenRequiredMessage = 'Please enter your API token.',
  authAccountSection = 'PikSend Account',
  
  -- Gallery (Requirements 3.1-3.10)
  galleryTitle = 'Gallery',
  gallerySelect = 'Select gallery',
  galleryCreate = 'New gallery',
  galleryRefresh = 'Refresh',
  galleryCreateTitle = 'Create new gallery',
  galleryTitleLabel = 'Title:',
  galleryDescriptionLabel = 'Description:',
  galleryPublic = 'Public gallery',
  galleryExpiration = 'Set expiration date',
  galleryExpiresIn = 'Expires in:',
  galleryDays = 'days',
  galleryPassword = 'Password protect',
  galleryPasswordLabel = 'Password:',
  galleryCreated = 'Gallery created',
  galleryCreatedMessage = 'Gallery "$$/title" has been created successfully.',
  galleryError = 'Error',
  galleryErrorMessage = 'Unable to create gallery. Please try again.',
  galleryRequired = 'Gallery required',
  galleryRequiredMessage = 'Please select or create a destination gallery.',
  galleryInvalidTitle = 'Invalid title',
  galleryInvalidTitleMessage = 'Gallery title must be between 1 and 200 characters.',
  galleryDestination = 'Destination Gallery',
  galleryPikSend = 'PikSend Gallery',
  gallerySyncDescription = 'This collection will be synchronized with a PikSend gallery.',
  galleryWatermark = 'Watermark',
  galleryWatermarkEnabled = 'Enable watermark',
  
  -- Export (Requirements 4.1-4.10, 5.1-5.10)
  exportTitle = 'Export to PikSend',
  exportSettings = 'Export settings',
  exportFormat = 'Format:',
  exportQuality = 'JPEG Quality:',
  exportMetadata = 'Include metadata',
  exportGPS = 'Include GPS location',
  exportProgress = 'Uploading to PikSend',
  exportComplete = 'Export complete',
  exportCompleteMessage = '$$/count photo(s) uploaded successfully to gallery "$$/gallery".\n\nLink: $$/url',
  exportCompleteWithErrors = 'Export complete with errors',
  exportCompleteWithErrorsMessage = '$$/success photo(s) uploaded, $$/failed failed.\n\nLink: $$/url',
  exportFailed = 'Upload failed',
  exportResize = 'Resize images',
  exportMaxWidth = 'Max width:',
  exportMaxHeight = 'Max height:',
  exportPixels = 'px',
  exportFormatJPEG = 'JPEG',
  exportFormatPNG = 'PNG',
  exportFormatTIFF = 'TIFF',
  
  -- Progress (Requirements 6.1-6.10)
  progressPreparing = 'Preparing...',
  progressUploading = 'Uploading... $$/current/$$/total photos',
  progressPaused = 'Paused',
  progressCancelled = 'Cancelled',
  progressPhotos = 'Photos:',
  progressSize = 'Size:',
  progressSpeed = 'Speed:',
  progressTimeRemaining = 'Time remaining:',
  progressPause = 'Pause',
  progressResume = 'Resume',
  progressCancel = 'Cancel',
  progressTitle = 'Progress:',
  progressPhotoDetails = 'Photo details',
  progressUploadingTo = 'Uploading to PikSend',
  progressPublishingTo = 'Publishing to PikSend',
  
  -- Publish Service (Requirements 7.1-7.10)
  publishTitle = 'Publish to PikSend',
  publishModified = 'Modified',
  publishToPublish = 'To publish',
  publishPublished = 'Published',
  publishError = 'Error',
  publishSyncConflict = 'Synchronization conflict',
  publishSyncConflictMessage = 'Some photos have been deleted on PikSend but are still present in Lightroom. What would you like to do?',
  publishKeepLocal = 'Keep in Lightroom',
  publishDeleteLocal = 'Delete from Lightroom',
  publishRepublish = 'Republish',
  
  -- Metadata (Requirements 8.1-8.10)
  metadataTitle = 'Metadata',
  metadataIncludeTitle = 'Include title',
  metadataIncludeDescription = 'Include description',
  metadataIncludeKeywords = 'Include keywords',
  metadataIncludeCopyright = 'Include copyright',
  metadataIncludeEXIF = 'Include EXIF data',
  metadataIncludeGPS = 'Include GPS location',
  metadataDefaultTitle = 'Default title:',
  metadataDefaultDescription = 'Default description:',
  
  -- Settings (Requirements 9.1-9.10, 11.1-11.11)
  settingsTitle = 'Settings',
  settingsDebugMode = 'Debug mode (detailed logs)',
  settingsLogs = 'Log management',
  settingsLogFile = 'Log file:',
  settingsViewLogs = 'View logs',
  settingsClearLogs = 'Clear logs',
  settingsClearLogsConfirm = 'Are you sure you want to clear all logs?',
  settingsLogsCleared = 'Logs cleared',
  settingsLogsClearedMessage = 'Logs have been cleared successfully.',
  settingsCache = 'Cache management',
  settingsClearCache = 'Clear cache',
  settingsClearCacheConfirm = 'Are you sure you want to clear the cache? This will remove gallery information and duplicate detection data.',
  settingsCacheCleared = 'Cache cleared',
  settingsCacheClearedMessage = 'Cache has been cleared successfully.',
  settingsCacheStats = 'Cache statistics',
  settingsMaxConcurrentUploads = 'Maximum concurrent uploads:',
  settingsPerformance = 'Performance',
  
  -- Updates (Requirements 12.1-12.10)
  updatesTitle = 'Updates',
  updatesCurrentVersion = 'Current version:',
  updatesNewVersion = 'New version:',
  updatesCheck = 'Check for updates',
  updatesAvailable = 'Update available',
  updatesAvailableTitle = 'A new version of the PikSend plugin is available!',
  updatesAvailableMessage = 'A new version is available: $$/version\n\n$$/changelog',
  updatesDownload = 'Download',
  updatesDownloadNow = 'Would you like to download the new version now?',
  updatesLater = 'Later',
  updatesNone = 'No updates',
  updatesNoneMessage = 'You are using the latest version of the plugin.',
  updatesReleaseNotes = 'Release notes:',
  updatesCheckingForUpdates = 'Checking for updates...',
  updatesError = 'Update check failed',
  updatesErrorMessage = 'Unable to check for updates. Please try again later.',
  
  -- Documentation and Support (Requirements 13.1-13.10)
  helpTitle = 'Help',
  helpDocumentation = 'Documentation',
  helpSupport = 'Support',
  helpWebsite = 'Website',
  helpForum = 'Community Forum',
  helpInstallationGuide = 'Installation Guide',
  helpUserGuide = 'User Guide',
  helpFAQ = 'FAQ',
  helpVideoTutorials = 'Video Tutorials',
  helpContactSupport = 'Contact Support',
  helpReportBug = 'Report a Bug',
  
  -- Tooltips (Requirement 13.9)
  tooltipAPIToken = 'Your API token can be generated from your PikSend dashboard. It allows the plugin to securely communicate with your PikSend account.',
  tooltipGalleryTitle = 'The gallery title must be between 1 and 200 characters.',
  tooltipGalleryExpiration = 'Set an expiration date for your gallery. After this date, the gallery will no longer be accessible.',
  tooltipGalleryPassword = 'Protect your gallery with a password. Viewers will need to enter this password to access the gallery.',
  tooltipJPEGQuality = 'JPEG quality from 1 (lowest) to 100 (highest). Higher quality means larger file sizes.',
  tooltipResize = 'Resize images before uploading. This can reduce upload time and storage space.',
  tooltipMetadata = 'Include photo metadata (title, description, keywords, EXIF) when uploading.',
  tooltipGPS = 'Include GPS location data in the uploaded photos. Disable this for privacy.',
  tooltipDebugMode = 'Enable detailed logging for troubleshooting. This will create larger log files.',
  tooltipMaxConcurrentUploads = 'Number of photos to upload simultaneously (1-5). Higher values may be faster but use more bandwidth.',
  
  -- Errors (Requirements 9.1-9.10)
  errorNetworkTimeout = 'Network timeout',
  errorNetworkTimeoutMessage = 'The connection timed out. Please check your internet connection and try again.',
  errorConnectionLost = 'Connection lost',
  errorConnectionLostMessage = 'The connection to PikSend was lost. Please check your internet connection.',
  errorServerError = 'Server error',
  errorServerErrorMessage = 'PikSend server encountered an error. Please try again later.',
  errorQuotaExceeded = 'Storage quota exceeded',
  errorQuotaExceededMessage = 'Your storage quota has been exceeded. Please upgrade your plan or delete some photos.',
  errorFileTooLarge = 'File too large',
  errorFileTooLargeMessage = 'The file "$$/filename" is too large ($$/size). Maximum file size is 500 MB.',
  errorUnsupportedFormat = 'Unsupported format',
  errorUnsupportedFormatMessage = 'The file format "$$/format" is not supported. Supported formats: JPEG, PNG, TIFF.',
  errorGalleryExpired = 'Gallery expired',
  errorGalleryExpiredMessage = 'The gallery "$$/gallery" has expired. Please create a new gallery.',
  errorPermissionDenied = 'Permission denied',
  errorPermissionDeniedMessage = 'Unable to write to "$$/path". Please check file permissions.',
  errorInsufficientMemory = 'Insufficient memory',
  errorInsufficientMemoryMessage = 'Not enough memory to complete the operation. Try reducing the number of concurrent uploads.',
  errorUnknown = 'Unknown error',
  errorUnknownMessage = 'An unexpected error occurred: $$/message',
  
  -- Presets (Requirements 4.8-4.9)
  presetTitle = 'Presets',
  presetSave = 'Save preset',
  presetLoad = 'Load preset',
  presetDelete = 'Delete preset',
  presetName = 'Preset name:',
  presetSaved = 'Preset saved',
  presetSavedMessage = 'Preset "$$/name" has been saved successfully.',
  presetLoaded = 'Preset loaded',
  presetLoadedMessage = 'Preset "$$/name" has been loaded successfully.',
  presetDeleted = 'Preset deleted',
  presetDeletedMessage = 'Preset "$$/name" has been deleted successfully.',
  presetDeleteConfirm = 'Are you sure you want to delete preset "$$/name"?',
  
  -- Common
  ok = 'OK',
  cancel = 'Cancel',
  yes = 'Yes',
  no = 'No',
  close = 'Close',
  save = 'Save',
  delete = 'Delete',
  retry = 'Retry',
  error = 'Error',
  warning = 'Warning',
  info = 'Info',
  success = 'Success',
  loading = 'Loading...',
  pleaseWait = 'Please wait...',
  
  -- Units
  unitBytes = 'B',
  unitKilobytes = 'KB',
  unitMegabytes = 'MB',
  unitGigabytes = 'GB',
  unitSeconds = 's',
  unitMinutes = 'min',
  unitHours = 'h',
  unitDays = 'days',
  unitPhotos = 'photo(s)',
  unitPerSecond = '/s',
}
