--[[----------------------------------------------------------------------------

fr.lua
Traductions françaises pour le plugin PikSend Lightroom

Couvre les exigences 13.1-13.10 pour la documentation et le support

------------------------------------------------------------------------------]]

return {
  -- Plugin info
  pluginName = 'PikSend',
  pluginDescription = 'Exportez vos photos directement vers PikSend depuis Lightroom',
  pluginVersion = 'Version: $$/version',
  pluginAbout = 'À propos de PikSend',
  pluginAboutDescription = 'Exportez vos photos directement vers PikSend depuis Lightroom.',
  pluginForLightroom = 'Plugin PikSend pour Adobe Lightroom Classic',
  
  -- Authentication (Exigences 2.1-2.10)
  authTitle = 'Connexion PikSend',
  authConnected = 'Connecté en tant que: $$/name',
  authNotConnected = 'Non connecté',
  authLogin = 'Connexion',
  authLogout = 'Déconnexion',
  authTokenLabel = 'Token API:',
  authTokenPlaceholder = 'Entrez votre token API',
  authOpenDashboard = 'Ouvrir le Dashboard',
  authInstructions = 'Générez un token API depuis votre dashboard PikSend:',
  authSuccess = 'Connexion réussie',
  authSuccessMessage = 'Bienvenue $$/name! Vous êtes maintenant connecté à PikSend.',
  authError = 'Erreur d\'authentification',
  authErrorMessage = 'Token API invalide. Veuillez vérifier votre token et réessayer.',
  authProRequired = 'Plan Pro requis',
  authProRequiredMessage = 'Le plugin Lightroom est réservé aux utilisateurs Pro. Veuillez upgrader votre plan sur piksend.com.',
  authTokenRequired = 'Token requis',
  authTokenRequiredMessage = 'Veuillez saisir votre token API.',
  authAccountSection = 'Compte PikSend',
  
  -- Gallery (Exigences 3.1-3.10)
  galleryTitle = 'Galerie',
  gallerySelect = 'Sélectionner une galerie',
  galleryCreate = 'Nouvelle galerie',
  galleryRefresh = 'Rafraîchir',
  galleryCreateTitle = 'Créer une nouvelle galerie',
  galleryTitleLabel = 'Titre:',
  galleryDescriptionLabel = 'Description:',
  galleryPublic = 'Galerie publique',
  galleryExpiration = 'Définir une date d\'expiration',
  galleryExpiresIn = 'Expire dans:',
  galleryDays = 'jours',
  galleryPassword = 'Protéger par mot de passe',
  galleryPasswordLabel = 'Mot de passe:',
  galleryCreated = 'Galerie créée',
  galleryCreatedMessage = 'La galerie "$$/title" a été créée avec succès.',
  galleryError = 'Erreur',
  galleryErrorMessage = 'Impossible de créer la galerie. Veuillez réessayer.',
  galleryRequired = 'Galerie requise',
  galleryRequiredMessage = 'Veuillez sélectionner ou créer une galerie de destination.',
  galleryInvalidTitle = 'Titre invalide',
  galleryInvalidTitleMessage = 'Le titre de la galerie doit contenir entre 1 et 200 caractères.',
  galleryDestination = 'Galerie de destination',
  galleryPikSend = 'Galerie PikSend',
  gallerySyncDescription = 'Cette collection sera synchronisée avec une galerie PikSend.',
  galleryWatermark = 'Filigrane',
  galleryWatermarkEnabled = 'Activer le filigrane',
  
  -- Export (Exigences 4.1-4.10, 5.1-5.10)
  exportTitle = 'Export vers PikSend',
  exportSettings = 'Paramètres d\'export',
  exportFormat = 'Format:',
  exportQuality = 'Qualité JPEG:',
  exportMetadata = 'Inclure les métadonnées',
  exportGPS = 'Inclure la géolocalisation (GPS)',
  exportProgress = 'Upload vers PikSend',
  exportComplete = 'Export terminé',
  exportCompleteMessage = '$$/count photo(s) uploadée(s) avec succès vers la galerie "$$/gallery".\n\nLien: $$/url',
  exportCompleteWithErrors = 'Export terminé avec erreurs',
  exportCompleteWithErrorsMessage = '$$/success photo(s) uploadée(s), $$/failed échec(s).\n\nLien: $$/url',
  exportFailed = 'Échec de l\'upload',
  exportResize = 'Redimensionner les images',
  exportMaxWidth = 'Largeur max:',
  exportMaxHeight = 'Hauteur max:',
  exportPixels = 'px',
  exportFormatJPEG = 'JPEG',
  exportFormatPNG = 'PNG',
  exportFormatTIFF = 'TIFF',
  
  -- Progress (Exigences 6.1-6.10)
  progressPreparing = 'Préparation...',
  progressUploading = 'Upload en cours... $$/current/$$/total photos',
  progressPaused = 'En pause',
  progressCancelled = 'Annulé',
  progressPhotos = 'Photos:',
  progressSize = 'Taille:',
  progressSpeed = 'Vitesse:',
  progressTimeRemaining = 'Temps restant:',
  progressPause = 'Pause',
  progressResume = 'Reprendre',
  progressCancel = 'Annuler',
  progressTitle = 'Progression:',
  progressPhotoDetails = 'Détails des photos',
  progressUploadingTo = 'Upload vers PikSend',
  progressPublishingTo = 'Publication vers PikSend',
  
  -- Publish Service (Exigences 7.1-7.10)
  publishTitle = 'Publier vers PikSend',
  publishModified = 'Modifié',
  publishToPublish = 'À publier',
  publishPublished = 'Publié',
  publishError = 'Erreur',
  publishSyncConflict = 'Conflit de synchronisation',
  publishSyncConflictMessage = 'Certaines photos ont été supprimées sur PikSend mais sont toujours présentes dans Lightroom. Que souhaitez-vous faire?',
  publishKeepLocal = 'Conserver dans Lightroom',
  publishDeleteLocal = 'Supprimer de Lightroom',
  publishRepublish = 'Republier',
  
  -- Metadata (Exigences 8.1-8.10)
  metadataTitle = 'Métadonnées',
  metadataIncludeTitle = 'Inclure le titre',
  metadataIncludeDescription = 'Inclure la description',
  metadataIncludeKeywords = 'Inclure les mots-clés',
  metadataIncludeCopyright = 'Inclure le copyright',
  metadataIncludeEXIF = 'Inclure les données EXIF',
  metadataIncludeGPS = 'Inclure la géolocalisation',
  metadataDefaultTitle = 'Titre par défaut:',
  metadataDefaultDescription = 'Description par défaut:',
  
  -- Settings (Exigences 9.1-9.10, 11.1-11.11)
  settingsTitle = 'Paramètres',
  settingsDebugMode = 'Mode debug (logs détaillés)',
  settingsLogs = 'Gestion des logs',
  settingsLogFile = 'Fichier de log:',
  settingsViewLogs = 'Voir les logs',
  settingsClearLogs = 'Effacer les logs',
  settingsClearLogsConfirm = 'Êtes-vous sûr de vouloir effacer tous les logs?',
  settingsLogsCleared = 'Logs effacés',
  settingsLogsClearedMessage = 'Les logs ont été effacés avec succès.',
  settingsCache = 'Gestion du cache',
  settingsClearCache = 'Effacer le cache',
  settingsClearCacheConfirm = 'Êtes-vous sûr de vouloir effacer le cache? Cela supprimera les informations de galeries et de doublons.',
  settingsCacheCleared = 'Cache effacé',
  settingsCacheClearedMessage = 'Le cache a été effacé avec succès.',
  settingsCacheStats = 'Statistiques du cache',
  settingsMaxConcurrentUploads = 'Nombre maximum d\'uploads simultanés:',
  settingsPerformance = 'Performance',
  
  -- Updates (Exigences 12.1-12.10)
  updatesTitle = 'Mises à jour',
  updatesCurrentVersion = 'Version actuelle:',
  updatesNewVersion = 'Nouvelle version:',
  updatesCheck = 'Vérifier les mises à jour',
  updatesAvailable = 'Mise à jour disponible',
  updatesAvailableTitle = 'Une nouvelle version du plugin PikSend est disponible!',
  updatesAvailableMessage = 'Une nouvelle version est disponible: $$/version\n\n$$/changelog',
  updatesDownload = 'Télécharger',
  updatesDownloadNow = 'Voulez-vous télécharger la nouvelle version maintenant?',
  updatesLater = 'Plus tard',
  updatesNone = 'Aucune mise à jour',
  updatesNoneMessage = 'Vous utilisez la dernière version du plugin.',
  updatesReleaseNotes = 'Notes de version:',
  updatesCheckingForUpdates = 'Vérification des mises à jour...',
  updatesError = 'Échec de la vérification',
  updatesErrorMessage = 'Impossible de vérifier les mises à jour. Veuillez réessayer plus tard.',
  
  -- Documentation and Support (Exigences 13.1-13.10)
  helpTitle = 'Aide',
  helpDocumentation = 'Documentation',
  helpSupport = 'Support',
  helpWebsite = 'Site Web',
  helpForum = 'Forum Communautaire',
  helpInstallationGuide = 'Guide d\'Installation',
  helpUserGuide = 'Guide d\'Utilisation',
  helpFAQ = 'FAQ',
  helpVideoTutorials = 'Tutoriels Vidéo',
  helpContactSupport = 'Contacter le Support',
  helpReportBug = 'Signaler un Bug',
  
  -- Tooltips (Exigence 13.9)
  tooltipAPIToken = 'Votre token API peut être généré depuis votre dashboard PikSend. Il permet au plugin de communiquer de manière sécurisée avec votre compte PikSend.',
  tooltipGalleryTitle = 'Le titre de la galerie doit contenir entre 1 et 200 caractères.',
  tooltipGalleryExpiration = 'Définissez une date d\'expiration pour votre galerie. Après cette date, la galerie ne sera plus accessible.',
  tooltipGalleryPassword = 'Protégez votre galerie avec un mot de passe. Les visiteurs devront saisir ce mot de passe pour accéder à la galerie.',
  tooltipJPEGQuality = 'Qualité JPEG de 1 (la plus basse) à 100 (la plus haute). Une qualité plus élevée signifie des fichiers plus volumineux.',
  tooltipResize = 'Redimensionnez les images avant l\'upload. Cela peut réduire le temps d\'upload et l\'espace de stockage.',
  tooltipMetadata = 'Incluez les métadonnées des photos (titre, description, mots-clés, EXIF) lors de l\'upload.',
  tooltipGPS = 'Incluez les données de géolocalisation GPS dans les photos uploadées. Désactivez cette option pour la confidentialité.',
  tooltipDebugMode = 'Activez les logs détaillés pour le dépannage. Cela créera des fichiers de log plus volumineux.',
  tooltipMaxConcurrentUploads = 'Nombre de photos à uploader simultanément (1-5). Des valeurs plus élevées peuvent être plus rapides mais utilisent plus de bande passante.',
  
  -- Errors (Exigences 9.1-9.10)
  errorNetworkTimeout = 'Délai d\'attente réseau',
  errorNetworkTimeoutMessage = 'La connexion a expiré. Veuillez vérifier votre connexion internet et réessayer.',
  errorConnectionLost = 'Connexion perdue',
  errorConnectionLostMessage = 'La connexion à PikSend a été perdue. Veuillez vérifier votre connexion internet.',
  errorServerError = 'Erreur serveur',
  errorServerErrorMessage = 'Le serveur PikSend a rencontré une erreur. Veuillez réessayer plus tard.',
  errorQuotaExceeded = 'Quota de stockage dépassé',
  errorQuotaExceededMessage = 'Votre quota de stockage a été dépassé. Veuillez upgrader votre plan ou supprimer des photos.',
  errorFileTooLarge = 'Fichier trop volumineux',
  errorFileTooLargeMessage = 'Le fichier "$$/filename" est trop volumineux ($$/size). La taille maximale est de 500 MB.',
  errorUnsupportedFormat = 'Format non supporté',
  errorUnsupportedFormatMessage = 'Le format de fichier "$$/format" n\'est pas supporté. Formats supportés: JPEG, PNG, TIFF.',
  errorGalleryExpired = 'Galerie expirée',
  errorGalleryExpiredMessage = 'La galerie "$$/gallery" a expiré. Veuillez créer une nouvelle galerie.',
  errorPermissionDenied = 'Permission refusée',
  errorPermissionDeniedMessage = 'Impossible d\'écrire dans "$$/path". Veuillez vérifier les permissions du fichier.',
  errorInsufficientMemory = 'Mémoire insuffisante',
  errorInsufficientMemoryMessage = 'Pas assez de mémoire pour terminer l\'opération. Essayez de réduire le nombre d\'uploads simultanés.',
  errorUnknown = 'Erreur inconnue',
  errorUnknownMessage = 'Une erreur inattendue s\'est produite: $$/message',
  
  -- Presets (Exigences 4.8-4.9)
  presetTitle = 'Préréglages',
  presetSave = 'Enregistrer le préréglage',
  presetLoad = 'Charger le préréglage',
  presetDelete = 'Supprimer le préréglage',
  presetName = 'Nom du préréglage:',
  presetSaved = 'Préréglage enregistré',
  presetSavedMessage = 'Le préréglage "$$/name" a été enregistré avec succès.',
  presetLoaded = 'Préréglage chargé',
  presetLoadedMessage = 'Le préréglage "$$/name" a été chargé avec succès.',
  presetDeleted = 'Préréglage supprimé',
  presetDeletedMessage = 'Le préréglage "$$/name" a été supprimé avec succès.',
  presetDeleteConfirm = 'Êtes-vous sûr de vouloir supprimer le préréglage "$$/name"?',
  
  -- Common
  ok = 'OK',
  cancel = 'Annuler',
  yes = 'Oui',
  no = 'Non',
  close = 'Fermer',
  save = 'Enregistrer',
  delete = 'Supprimer',
  retry = 'Réessayer',
  error = 'Erreur',
  warning = 'Avertissement',
  info = 'Info',
  success = 'Succès',
  loading = 'Chargement...',
  pleaseWait = 'Veuillez patienter...',
  
  -- Units
  unitBytes = 'o',
  unitKilobytes = 'Ko',
  unitMegabytes = 'Mo',
  unitGigabytes = 'Go',
  unitSeconds = 's',
  unitMinutes = 'min',
  unitHours = 'h',
  unitDays = 'jours',
  unitPhotos = 'photo(s)',
  unitPerSecond = '/s',
}
